# Nginx webserver
# https://hub.docker.com/_/nginx

FROM nginx:1.18-alpine
EXPOSE 8880

COPY webfiles/* /usr/share/nginx/html/
COPY nginx.conf /etc/nginx/nginx.conf
RUN chmod 644 /etc/nginx/nginx.conf && \
    chown root:root /etc/nginx/nginx.conf

USER nginx