#
# ttyd - Share your terminal over the web
# https://github.com/tsl0922/ttyd
#

FROM tsl0922/ttyd

EXPOSE 7681

ENV DEBIAN_FRONTEND noninteractive
RUN apt update && \
    apt-get install -y tmux vim ncmpcpp mpc mc curl && \ 
    apt-get clean

# create a non-root user
RUN groupadd -r dj && \
    useradd -r -g dj -d /home/dj -s /bin/bash -c "dj" dj && \
    adduser dj audio

RUN mkdir -pv /home/dj/.ncmpcpp && \
    touch /home/dj/.ncmpcpp/config && \
    echo 'mpd_host = backendmpd' >> /home/dj/.ncmpcpp/config && \
    echo 'mpd_port = 6600' >> /home/dj/.ncmpcpp/config && \
    touch /home/dj/.vimrc && \
    echo 'set laststatus=2' >> /home/dj/.vimrc && \
    echo 'syntax on' >> /home/dj/.vimrc && \
    echo 'set number' >> /home/dj/.vimrc && \
    touch /home/dj/.tmux.conf && \
    echo 'set -g default-terminal "screen-256color"' >> /home/dj/.tmux.conf && \
    echo 'set -g mouse on' >> /home/dj/.tmux.conf && \
    echo 'set -g base-index 1' >> /home/dj/.tmux.conf && \
    chown dj:dj -R /home/dj && \
    chmod 770 /home/dj

RUN touch /etc/profile.d/10-alias.sh && \
    echo "alias mpc='mpc -h backendmpd'" >> /etc/profile.d/10-alias.sh

COPY shell-entrypoint.sh /shell-entrypoint.sh

USER dj
WORKDIR /home/dj
COPY shell-entrypoint.sh ./

# start tini first ( https://github.com/krallin/tini )
ENTRYPOINT ["/sbin/tini", "--"]

CMD ["/shell-entrypoint.sh"]
