# Nginx webserver
# https://hub.docker.com/_/nginx

FROM nginx:1.18-alpine
EXPOSE 8880

COPY nginx.conf /etc/nginx/nginx.conf

RUN chmod 644 /etc/nginx/nginx.conf && \
    chown root:root /etc/nginx/nginx.conf && \
    mkdir -pv /var/cache/nginx/client_temp && \
    chmod 600 /var/cache/nginx/client_temp && \
    mkdir -pv /var/cache/nginx/proxy_temp && \
    chmod 600 /var/cache/nginx/proxy_temp && \
    chown nginx:root /var/cache/nginx/client_temp && \
    chown nginx:root /var/run && \
    chmod 775 /var/run

COPY webfiles/* /usr/share/nginx/html/

RUN find /usr/share/nginx/html/ -type d -exec chmod 775 {} \;
RUN find /usr/share/nginx/html/ -type f -exec chmod 644 {} \;
RUN chown root:root /usr/share/nginx/html/*

USER nginx
