# Python3 MPContainer PyApp
# https://hub.docker.com/_/python

FROM python:3-slim-buster
EXPOSE 8888/tcp

LABEL mpcontainer.vendor="Music Player Container"
LABEL version="1.0"
LABEL mpcontainer.service="mpc python3 flask app"

RUN groupadd -r pyapp && \
    useradd -r -g pyapp -d /app -s /sbin/nologin -c "pyapp" pyapp

ENV HOME=/pyapp
COPY pyapp /pyapp
WORKDIR /pyapp

RUN find /pyapp -type d -exec chmod 775 {} \;
RUN find /pyapp -type f -exec chmod 644 {} \;

# install app requirements
RUN pip install -r /pyapp/requirements.txt

USER pyapp

# run in debug mode?
ARG mpcpyapp_debug=false
ENV env_mpcpyapp_debug=$mpcpyapp_debug

# entry point - launch gunicorn
CMD ["bash", "/pyapp/start.sh"]
