# MPContainer Dev VM

Vagrant.require_version ">= 2.2.14"

$inlinescript_post = <<-SCRIPT
echo '-----------------------';
uname -a;
myip=$(ifconfig eth0 | grep inet | grep -v inet6 | tr -s " ")
echo "My IP: ${myip}";
echo '-----------------------';
SCRIPT

Vagrant.configure("2") do |config|

    # --- Ubuntu ---
    config.vm.box = "generic/ubuntu1804"
    config.vm.box_version = "3.2.16"
    # --- CentOS ---
    #config.vm.box = "generic/centos8"
    #config.vm.box_version = "3.2.16"

    config.vm.box_check_update = false
    config.vm.synced_folder "../", "/vagrant", type: "rsync"

    config.vm.provision "ansible_local" do |ansible|
        ansible.playbook = "vagrant-dev-vm/ansible-playbook.yml"
    end

    config.vm.network :forwarded_port, guest: 9090, host_ip: '127.0.0.1', host: 33339, protocol: "tcp"
    config.vm.network :forwarded_port, guest: 3000, host_ip: '127.0.0.1', host: 33333, protocol: "tcp"

    config.trigger.after [:up, :provision, :resume, :reload] do |t|
        t.info = "running inlinescript_post"
        t.run_remote = {inline: $inlinescript_post, :privileged => false}
    end

end

# -*- mode: ruby -*-
# vi: ft=ruby :