apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config-claim
  namespace: musicplayer
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: slow
  volumeMode: Filesystem
  resources:
    requests:
      storage: 2G
  selector:
    matchLabels:
      type: "config"
