name: build-container-pyapp
# build this container and push to Github registry
on:

  push:
    branches: [ master ]
    paths:
      - './src/pyapp/**'

jobs:

  container-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: docker_login
      env:
        GIT_UN: ${{ secrets.GIT_UN }}
        GIT_TOKE: ${{ secrets.GIT_TOKE }}
      run: |
        echo $GIT_TOKE | docker login https://ghcr.io/ -u $GIT_UN --password-stdin

    - name: build_container
      env:
        GIT_UN: ${{ secrets.GIT_UN }}
      run: |
        docker build -t mpcontainer-pyapp:latest --build-arg env_mpypyapp_envtest=defaultprod2 -f ./src/pyapp/Dockerfile ./src/pyapp/
        docker tag mpcontainer-pyapp ghcr.io/$GIT_UN/mpcontainer-pyapp

    - name: list_docker_images
      run: |
        docker images

    - name: push_images_GitHub_reg
      env:
        GIT_UN: ${{ secrets.GIT_UN }}
      run: |
        docker push ghcr.io/$GIT_UN/mpcontainer-pyapp:latest